name: Build Modpack ZIP

on:
  push:
    branches:
      - main  # roda sempre que fizer push no branch main
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o repositório
      - name: Checar código
        uses: actions/checkout@v3

      # Criar ZIP do modpack diretamente da raiz
      - name: Criar ZIP do modpack
        run: |
          zip -r NexusSMP-Pack.zip . -x ".git*" ".github/*"

      # Salvar ZIP como artefato
      - name: Salvar ZIP como artefato
        uses: actions/upload-artifact@v4
        with:
          name: NexusSMP-Pack
          path: NexusSMP-Pack.zip
