name: Build Modpack ZIP

on:
  push:
    branches:
      - main  # roda sempre que fizer push no branch main
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o repositório
      - name: Checar código
        uses: actions/checkout@v3

      # Criar ZIP do modpack diretamente da raiz
      # O comando zipa tudo (-r) a partir do diretório atual (.)
      # e exclui (-x) as pastas .git, .github E o próprio arquivo .zip antigo
      - name: Criar ZIP do modpack
        run: |
          zip -r NexusSMP-Pack.zip . -x ".git*" ".github/*" "NexusSMP-Pack.zip"

      # Salvar ZIP como artefato
      - name: Salvar ZIP como artefato
        uses: actions/upload-artifact@v4
        with:
          name: NexusSMP-Pack # Nome do artefato que aparecerá no GitHub
          path: NexusSMP-Pack.zip # Caminho para o arquivo que deve ser salvo

